# This is a basic workflow to help you get started with Actions

name: royal-oak

on: 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: [self-hosted, royal-oak]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Automates the deployment of the midas-api repository & runs database migraions 
        shell: powershell
        run: | 
            C:\DeploymentAutomation\QuickDeployTest\AutomateDeploy.ps1
            cd C:\DeploymentAutomation\QuickDeployTest\Source\db-migration
            flyway migrate
